services:
  timescale:
    image: timescale/timescaledb:2.23.0-pg18
    container_name: timescale-spring-react-app
    ports:
      - "5432:5432"
    volumes:
      - timescale-spring-react-app-data:/home/postgres/pgdata/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: spring-react-app
volumes:
  timescale-spring-react-app-data: